export enum EClub {
  CREATIVE_CLUB = "CREATIVE_ACTIVITY_CLUB",
  SELF_DIRECT_CLUB = "SELF_DIRECT_ACTIVITY_CLUB"
}

export enum EClubState {
  ALLOWED = "ALLOWED",
  PENDING = "PENDING",
  REJECTED = "REJECTED",
  WAITING = "WAITING",
  DELETED = "DELETED"
}